server {
    listen 80;                          # nginx escuta na porta 80 dentro do container
    index index.php index.html;         # arquivo padrão ao acessar uma pasta
    root /var/www/html/public;          # raiz pública do Laravel é a pasta /public

    # qualquer rota que não seja um arquivo físico existente
    # cai no index.php - é assim que o roteamento do Laravel funciona
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # toda URL terminada em .php é repassada pro PHP-FPM processar
    location ~ \.php$ {
        fastcgi_pass php:9000;
                                  # "php" é o NOME DO SERVIÇO no docker-compose.yml
                                  # o Docker resolve isso como endereço de rede interno automaticamente
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/$fastcgi_script_name;
        include fastcgi_params;
    }
}